name: flutter_lqrui
description: lqr ui
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_picker: ^1.1.0 #选择器
  multi_image_picker: ^4.5.9 #多图片选择
  image_picker: ^0.6.2 #图片选择，相册或拍照
  file_picker: ^1.4.3+1 #文件选择
  flustars: ^0.2.6+1 #Flutter常用工具类库
  fluttertoast: ^3.1.3 #Toast轻提示
  uuid: ^2.0.4
  flutter_spinkit: ^4.0.0 #加载动画指示器
  flutter_easyrefresh: ^2.0.4 #上拉加载
  # cached_network_image: ^1.1.3 #缓存图片
  cached_network_image:
    git: 
      url: https://github.com/renefloor/flutter_cached_network_image.git
  url_launcher: ^5.2.5 #链接跳转 
  dio: ^3.0.5 #ajax 
  photo_view: ^0.8.2  #图片预览

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  plugin:
    androidPackage: com.lqrui.flutter_lqrui
    pluginClass: FlutterLqruiPlugin
